wds_api_auth_authenticate_without_slash: &wds_api_auth_authenticate_without_slash
    path:     /authenticate
    methods:  [ OPTIONS, POST ]
    controller: WernerDweight\ApiAuthBundle\Controller\AuthenticateController::index
    defaults:
        _format: json

wds_api_auth_authenticate_with_slash:
    <<: *wds_api_auth_authenticate_without_slash
    path: /authenticate/
