services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\ApiAuthBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Enum,Event,Exception}'

    WernerDweight\ApiAuthBundle\Service\ConfigurationProvider:
        arguments:
            $targetControllers: '%api_auth.target_controllers%'

    WernerDweight\ApiAuthBundle\Security\ApiClientProvider:
        arguments:
            $apiClientClassName: '%api_auth.client.class%'
            $property: '%api_auth.client.property%'
