services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\ApiAuthBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Enum,Event,Exception}'

    WernerDweight\ApiAuthBundle\Service\ConfigurationProvider:
        arguments:
            $clientClass: '%api_auth.client.class%'
            $clientProperty: '%api_auth.client.property%'
            $clientUseScopeAccessModel: '%api_auth.client.use_scope_access_model%'
            $clientAccessScopeChecker: '%api_auth.client.access_scope_checker%'
            $userClass: '%api_auth.user.class%'
            $userToken: '%api_auth.user.token%'
            $userLoginProperty: '%api_auth.user.login_property%'
            $userApiTokenExpirationInterval: '%api_auth.user.api_token_expiration_interval%'
            $userUseScopeAccessModel: '%api_auth.user.use_scope_access_model%'
            $userAccessScopeChecker: '%api_auth.user.access_scope_checker%'
            $targetControllers: '%api_auth.target_controllers%'
            $excludeOptionsRequests: '%api_auth.exclude_options_requests%'

    WernerDweight\ApiAuthBundle\Service\AccessScopeChecker\Checker\:
        resource: '../../Service/AccessScopeChecker/Checker/*'
        exclude: '../../Service/AccessScopeChecker/Checker/Abstract*'
        tags:
            - { name: 'api_auth.access_scope_checker' }

    WernerDweight\ApiAuthBundle\Service\AccessScopeChecker\AccessScopeCheckerFactory:
        arguments:
            $scopeCheckers: !tagged api_auth.access_scope_checker

    WernerDweight\TokenGenerator\TokenGenerator: ~
